import React from "react"

let Par = (props)=>{
    return(<p className="light-shade">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut blandit ex enim, vel vulputate dolor blandit sit amet. Sed egestas lectus vitae tortor efficitur rutrum. Pellentesque et elit sed orci semper elementum sit amet vel risus. Sed arcu odio, placerat nec est quis, tempor tincidunt est. Sed at massa vel nisl bibendum bibendum non quis odio. Donec velit justo, porta sit amet elit feugiat, pulvinar rutrum magna. In congue purus in metus gravida ultricies. Vivamus nec maximus orci. Morbi nec elit vitae orci sagittis tempor in at elit. In pharetra libero velit, vel egestas elit dignissim nec. Sed ipsum magna, bibendum id diam et, faucibus porttitor tellus. Aenean eget nisi at magna aliquet hendrerit. Nullam et efficitur lectus.

Nullam at ligula magna. Proin neque lacus, eleifend a convallis sit amet, fringilla sed mauris. Sed id placerat velit. Donec sit amet venenatis ipsum. Donec pharetra rutrum scelerisque. Integer sodales lacus ex, nec malesuada tellus tincidunt a. Morbi aliquet, urna in scelerisque sagittis, ipsum quam condimentum magna, vitae vehicula nisl libero vel orci. Phasellus laoreet ornare neque, ac tempor augue pulvinar quis. Curabitur dapibus nunc ac est feugiat, sit amet sollicitudin leo posuere. Ut cursus tristique dignissim. Suspendisse in lectus scelerisque, tempus erat euismod, suscipit diam. Aenean malesuada orci magna, non suscipit augue lobortis vitae. Vivamus eu turpis suscipit, gravida lacus non, bibendum lorem.

Praesent tincidunt tempus interdum. Nam ligula lorem, cursus ut tincidunt eget, facilisis efficitur nisi. Mauris nibh ipsum, egestas sed augue vel, dictum accumsan augue. Donec ac risus ut augue rhoncus volutpat fringilla et sapien. Pellentesque egestas fermentum arcu, eget ornare ligula sollicitudin quis. Pellentesque fringilla, dui at mattis faucibus, nibh augue feugiat lorem, eu posuere neque mauris id lorem. Ut vitae gravida urna, id feugiat ante. Phasellus sagittis, ante in convallis sollicitudin, ex velit congue magna, consequat ultrices magna sem eget orci. Sed sit amet rutrum massa. Pellentesque eget tincidunt est, et condimentum diam. Proin eu diam metus. Vestibulum a mi et sem rutrum commodo in id libero. Sed pellentesque dui ut leo ultricies aliquet. Integer nec tortor at nunc rhoncus tempor id sit amet dolor. Sed dictum fermentum justo, interdum aliquet ipsum. Nam dignissim in felis in suscipit.

Sed congue consequat suscipit. Aenean eleifend massa in enim malesuada, id pellentesque dolor bibendum. Nunc pretium, lorem at tincidunt maximus, nulla massa vehicula ipsum, vel consequat nisi nisl quis urna. Aliquam facilisis ex quis nibh scelerisque rutrum. Sed in pretium quam, sed facilisis eros. Sed ornare, elit eu tempor faucibus, mauris est placerat risus, in sodales risus sem vel risus. Vestibulum tristique tellus at velit egestas, vel posuere lorem tristique. Nullam volutpat lectus vitae congue bibendum. Curabitur urna massa, porttitor at pretium id, molestie quis orci. Curabitur laoreet purus ac elementum convallis. Aenean nec ligula vel ipsum sodales condimentum id sit amet tortor. Aliquam sit amet euismod orci, sit amet vestibulum libero.

Nulla facilisi. Donec turpis augue, tristique in nisl eu, semper vehicula enim. Donec bibendum a nulla sed bibendum. Quisque in viverra sapien. Nunc pretium porttitor arcu sed ullamcorper. Fusce ornare purus eget libero rutrum, in placerat tortor vestibulum. Nunc sit amet sem eget eros efficitur vehicula at nec ipsum. Maecenas aliquet magna felis, ut finibus diam ornare vehicula. Duis commodo gravida libero sit amet rutrum. Nulla sed posuere ex. Integer a finibus velit. Quisque malesuada sodales est nec suscipit. Curabitur euismod at odio non aliquet.
    </p>)
}

export default Par